Initial commit

diff --git a/build/azure-pipelines/linux/product-build-linux.yml b/build/azure-pipelines/linux/product-build-linux.yml
--- a/build/azure-pipelines/linux/product-build-linux.yml
+++ b/build/azure-pipelines/linux/product-build-linux.yml
@@ -27,7 +27,7 @@ steps:
   - ${{ if ne(parameters.VSCODE_QUALITY, 'oss') }}:
     - template: ../distro/download-distro.yml@self
 
-    - task: AzureKeyVault@2
+    - task: AzureKeyVault@1
       displayName: "Azure Key Vault: Get Secrets"
       inputs:
         azureSubscription: "vscode-builds-subscription"
@@ -46,8 +46,8 @@ steps:
   - script: |
       set -e
       # Start X server
-      ./build/azure-pipelines/linux/apt-retry.sh sudo apt-get update
-      ./build/azure-pipelines/linux/apt-retry.sh sudo apt-get install -y pkg-config \
+      sudo apt-get update
+      sudo apt-get install -y pkg-config \
         dbus \
         xvfb \
         libgtk-3-0 \
@@ -69,12 +69,12 @@ steps:
     condition: and(succeeded(), ne(variables['NPM_REGISTRY'], 'none'))
     displayName: Setup NPM Registry
 
-  - script: mkdir -p .build && node build/azure-pipelines/common/computeNodeModulesCacheKey.js linux $VSCODE_ARCH > .build/packagelockhash
+  - script: mkdir -p .build && node build/azure-pipelines/common/computeNodeModulesCacheKey.js linux $VSCODE_ARCH > .build/yarnlockhash
     displayName: Prepare node_modules cache key
 
   - task: Cache@2
     inputs:
-      key: '"node_modules" | .build/packagelockhash'
+      key: '"node_modules" | .build/yarnlockhash'
       path: .build/node_modules_cache
       cacheHitVar: NODE_MODULES_RESTORED
     displayName: Restore node_modules cache
@@ -85,17 +85,18 @@ steps:
 
   - script: |
       set -e
-      # Set the private NPM registry to the global npmrc file
-      # so that authentication works for subfolders like build/, remote/, extensions/ etc
-      # which does not have their own .npmrc file
-      npm config set registry "$NPM_REGISTRY"
-      echo "##vso[task.setvariable variable=NPMRC_PATH]$(npm config get userconfig)"
+      npm config set registry "$NPM_REGISTRY" --location=project
+      # npm >v7 deprecated the `always-auth` config option, refs npm/cli@72a7eeb
+      # following is a workaround for yarn to send authorization header
+      # for GET requests to the registry.
+      echo "always-auth=true" >> .npmrc
+      yarn config set registry "$NPM_REGISTRY"
     condition: and(succeeded(), ne(variables.NODE_MODULES_RESTORED, 'true'), ne(variables['NPM_REGISTRY'], 'none'))
-    displayName: Setup NPM
+    displayName: Setup NPM & Yarn
 
   - task: npmAuthenticate@0
     inputs:
-      workingFile: $(NPMRC_PATH)
+      workingFile: .npmrc
     condition: and(succeeded(), ne(variables.NODE_MODULES_RESTORED, 'true'), ne(variables['NPM_REGISTRY'], 'none'))
     displayName: Setup NPM Authentication
 
@@ -103,66 +104,23 @@ steps:
       set -e
 
       for i in {1..5}; do # try 5 times
-        npm ci && break
-        if [ $i -eq 5 ]; then
-          echo "Npm install failed too many times" >&2
+        yarn --cwd build --frozen-lockfile --check-files && break
+        if [ $i -eq 3 ]; then
+          echo "Yarn failed too many times" >&2
           exit 1
         fi
-        echo "Npm install failed $i, trying again..."
+        echo "Yarn failed $i, trying again..."
       done
-    workingDirectory: build
-    displayName: Install build dependencies
-    condition: and(succeeded(), ne(variables.NODE_MODULES_RESTORED, 'true'))
-
-  # Step will be used by both Install dependencies and building rpm package,
-  # hence avoid adding it behind NODE_MODULES_RESTORED condition.
-  - script: |
-      set -e
-      SYSROOT_ARCH=$VSCODE_ARCH
-      if [ "$SYSROOT_ARCH" == "x64" ]; then
-        SYSROOT_ARCH="amd64"
-      fi
-      export VSCODE_SYSROOT_DIR=$(Build.SourcesDirectory)/.build/sysroots
-      SYSROOT_ARCH="$SYSROOT_ARCH" node -e '(async () => { const { getVSCodeSysroot } = require("./build/linux/debian/install-sysroot.js"); await getVSCodeSysroot(process.env["SYSROOT_ARCH"]); })()'
-    env:
-      VSCODE_ARCH: $(VSCODE_ARCH)
-      GITHUB_TOKEN: "$(github-distro-mixin-password)"
-    displayName: Download vscode sysroots
-
-  - ${{ if or(eq(parameters.VSCODE_ARCH, 'arm64'), eq(parameters.VSCODE_ARCH, 'armhf')) }}:
-    - script: |
-        set -e
-        includes=$(cat << 'EOF'
-        {
-          "target_defaults": {
-            "conditions": [
-              ["OS=='linux'", {
-                'cflags_cc!': [ '-std=gnu++20' ],
-                'cflags_cc': [ '-std=gnu++2a' ],
-              }]
-            ]
-          }
-        }
-        EOF
-        )
-        if [ ! -d "$HOME/.gyp" ]; then
-          mkdir -p "$HOME/.gyp"
-        fi
-        echo "$includes" > "$HOME/.gyp/include.gypi"
-      displayName: Override gnu target for arm64 and arm
-
-  - script: |
-      set -e
 
       source ./build/azure-pipelines/linux/setup-env.sh
 
       for i in {1..5}; do # try 5 times
-        npm ci && break
-        if [ $i -eq 5 ]; then
-          echo "Npm install failed too many times" >&2
+        yarn --frozen-lockfile --check-files && break
+        if [ $i -eq 3 ]; then
+          echo "Yarn failed too many times" >&2
           exit 1
         fi
-        echo "Npm install failed $i, trying again..."
+        echo "Yarn failed $i, trying again..."
       done
     env:
       npm_config_arch: $(NPM_ARCH)
@@ -177,6 +135,20 @@ steps:
     - script: node build/azure-pipelines/distro/mixin-npm
       condition: and(succeeded(), ne(variables.NODE_MODULES_RESTORED, 'true'))
       displayName: Mixin distro node modules
+
+  - ${{ else }}:
+    # Ref https://github.com/microsoft/vscode/issues/189019
+    # for the node-gyp rebuild step
+    - script: |
+        set -e
+
+        cd node_modules/native-keymap && npx node-gyp@9.4.0 -y rebuild --debug
+        cd ../.. && ./.github/workflows/check-clean-git-state.sh
+      env:
+        npm_config_arch: $(NPM_ARCH)
+        GITHUB_TOKEN: "$(github-distro-mixin-password)"
+      displayName: Rebuild debug version of native modules (OSS)
+      condition: and(succeeded(), ne(variables.NODE_MODULES_RESTORED, 'true'))
 
   - script: |
       set -e
@@ -195,7 +167,7 @@ steps:
   - ${{ if ne(parameters.VSCODE_QUALITY, 'oss') }}:
     - script: |
         set -e
-        npm run gulp vscode-linux-$(VSCODE_ARCH)-min-ci
+        yarn gulp vscode-linux-$(VSCODE_ARCH)-min-ci
         ARCHIVE_PATH=".build/linux/client/code-${{ parameters.VSCODE_QUALITY }}-$(VSCODE_ARCH)-$(date +%s).tar.gz"
         mkdir -p $(dirname $ARCHIVE_PATH)
         echo "##vso[task.setvariable variable=CLIENT_PATH]$ARCHIVE_PATH"
@@ -228,7 +200,7 @@ steps:
 
     - script: |
         set -e
-        npm run gulp vscode-reh-linux-$(VSCODE_ARCH)-min-ci
+        yarn gulp vscode-reh-linux-$(VSCODE_ARCH)-min-ci
         mv ../vscode-reh-linux-$(VSCODE_ARCH) ../vscode-server-linux-$(VSCODE_ARCH) # TODO@joaomoreno
         ARCHIVE_PATH=".build/linux/server/vscode-server-linux-$(VSCODE_ARCH).tar.gz"
         UNARCHIVE_PATH="`pwd`/../vscode-server-linux-$(VSCODE_ARCH)"
@@ -242,7 +214,7 @@ steps:
 
     - script: |
         set -e
-        npm run gulp vscode-reh-web-linux-$(VSCODE_ARCH)-min-ci
+        yarn gulp vscode-reh-web-linux-$(VSCODE_ARCH)-min-ci
         mv ../vscode-reh-web-linux-$(VSCODE_ARCH) ../vscode-server-linux-$(VSCODE_ARCH)-web # TODO@joaomoreno
         ARCHIVE_PATH=".build/linux/web/vscode-server-linux-$(VSCODE_ARCH)-web.tar.gz"
         mkdir -p $(dirname $ARCHIVE_PATH)
@@ -255,6 +227,8 @@ steps:
     - ${{ if or(eq(parameters.VSCODE_ARCH, 'x64'), eq(parameters.VSCODE_ARCH, 'arm64')) }}:
       - script: |
           set -e
+
+          source ./build/azure-pipelines/linux/setup-env.sh
 
           EXPECTED_GLIBC_VERSION="2.28" \
           EXPECTED_GLIBCXX_VERSION="3.4.25" \
@@ -269,6 +243,8 @@ steps:
       - script: |
           set -e
 
+          source ./build/azure-pipelines/linux/setup-env.sh
+
           EXPECTED_GLIBC_VERSION="2.28" \
           EXPECTED_GLIBCXX_VERSION="3.4.26" \
           ./build/azure-pipelines/linux/verify-glibc-requirements.sh
@@ -279,7 +255,7 @@ steps:
         displayName: Check GLIBC and GLIBCXX dependencies in server archive
 
   - ${{ else }}:
-    - script: npm run gulp "transpile-client-esbuild" "transpile-extensions"
+    - script: yarn gulp "transpile-client-swc" "transpile-extensions"
       env:
         GITHUB_TOKEN: "$(github-distro-mixin-password)"
       displayName: Transpile client and extensions
@@ -297,48 +273,31 @@ steps:
   - ${{ if and(ne(parameters.VSCODE_CIBUILD, true), ne(parameters.VSCODE_QUALITY, 'oss')) }}:
     - script:  |
         set -e
-        npm run gulp "vscode-linux-$(VSCODE_ARCH)-prepare-deb"
+        yarn gulp "vscode-linux-$(VSCODE_ARCH)-prepare-deb"
       env:
         GITHUB_TOKEN: "$(github-distro-mixin-password)"
       displayName: Prepare deb package
 
     - script:  |
         set -e
-        npm run gulp "vscode-linux-$(VSCODE_ARCH)-build-deb"
-        file_output=$(file $(ls .build/linux/deb/*/deb/*.deb))
-        if [[ "$file_output" != *"data compression xz"* ]]; then
-          echo "Error: unknown compression. $file_output"
-          exit 1
-        fi
+        yarn gulp "vscode-linux-$(VSCODE_ARCH)-build-deb"
         echo "##vso[task.setvariable variable=DEB_PATH]$(ls .build/linux/deb/*/deb/*.deb)"
       displayName: Build deb package
 
     - script:  |
         set -e
-        TRIPLE=""
-        if [ "$VSCODE_ARCH" == "x64" ]; then
-          TRIPLE="x86_64-linux-gnu"
-        elif [ "$VSCODE_ARCH" == "arm64" ]; then
-          TRIPLE="aarch64-linux-gnu"
-        elif [ "$VSCODE_ARCH" == "armhf" ]; then
-          TRIPLE="arm-rpi-linux-gnueabihf"
-        fi
-        export VSCODE_SYSROOT_DIR=$(Build.SourcesDirectory)/.build/sysroots
-        export STRIP="$VSCODE_SYSROOT_DIR/$TRIPLE/$TRIPLE/bin/strip"
-        npm run gulp "vscode-linux-$(VSCODE_ARCH)-prepare-rpm"
-      env:
-        VSCODE_ARCH: $(VSCODE_ARCH)
+        yarn gulp "vscode-linux-$(VSCODE_ARCH)-prepare-rpm"
       displayName: Prepare rpm package
 
     - script:  |
         set -e
-        npm run gulp "vscode-linux-$(VSCODE_ARCH)-build-rpm"
+        yarn gulp "vscode-linux-$(VSCODE_ARCH)-build-rpm"
         echo "##vso[task.setvariable variable=RPM_PATH]$(ls .build/linux/rpm/*/*.rpm)"
       displayName: Build rpm package
 
     - script: |
         set -e
-        npm run gulp "vscode-linux-$(VSCODE_ARCH)-prepare-snap"
+        yarn gulp "vscode-linux-$(VSCODE_ARCH)-prepare-snap"
         ARCHIVE_PATH=".build/linux/snap-tarball/snap-$(VSCODE_ARCH).tar.gz"
         mkdir -p $(dirname $ARCHIVE_PATH)
         tar -czf $ARCHIVE_PATH -C .build/linux snap
diff --git a/build/azure-pipelines/product-compile.yml b/build/azure-pipelines/product-compile.yml
--- a/build/azure-pipelines/product-compile.yml
+++ b/build/azure-pipelines/product-compile.yml
@@ -12,7 +12,7 @@ steps:
   - ${{ if ne(parameters.VSCODE_QUALITY, 'oss') }}:
     - template: ./distro/download-distro.yml@self
 
-    - task: AzureKeyVault@2
+    - task: AzureKeyVault@1
       displayName: "Azure Key Vault: Get Secrets"
       inputs:
         azureSubscription: "vscode-builds-subscription"
@@ -23,12 +23,12 @@ steps:
     condition: and(succeeded(), ne(variables['NPM_REGISTRY'], 'none'))
     displayName: Setup NPM Registry
 
-  - script: mkdir -p .build && node build/azure-pipelines/common/computeNodeModulesCacheKey.js compile > .build/packagelockhash
+  - script: mkdir -p .build && node build/azure-pipelines/common/computeNodeModulesCacheKey.js compile > .build/yarnlockhash
     displayName: Prepare node_modules cache key
 
   - task: Cache@2
     inputs:
-      key: '"node_modules" | .build/packagelockhash'
+      key: '"node_modules" | .build/yarnlockhash'
       path: .build/node_modules_cache
       cacheHitVar: NODE_MODULES_RESTORED
     displayName: Restore node_modules cache
@@ -39,17 +39,18 @@ steps:
 
   - script: |
       set -e
-      # Set the private NPM registry to the global npmrc file
-      # so that authentication works for subfolders like build/, remote/, extensions/ etc
-      # which does not have their own .npmrc file
-      npm config set registry "$NPM_REGISTRY"
-      echo "##vso[task.setvariable variable=NPMRC_PATH]$(npm config get userconfig)"
+      npm config set registry "$NPM_REGISTRY" --location=project
+      # npm >v7 deprecated the `always-auth` config option, refs npm/cli@72a7eeb
+      # following is a workaround for yarn to send authorization header
+      # for GET requests to the registry.
+      echo "always-auth=true" >> .npmrc
+      yarn config set registry "$NPM_REGISTRY"
     condition: and(succeeded(), ne(variables.NODE_MODULES_RESTORED, 'true'), ne(variables['NPM_REGISTRY'], 'none'))
-    displayName: Setup NPM
+    displayName: Setup NPM & Yarn
 
   - task: npmAuthenticate@0
     inputs:
-      workingFile: $(NPMRC_PATH)
+      workingFile: .npmrc
     condition: and(succeeded(), ne(variables.NODE_MODULES_RESTORED, 'true'), ne(variables['NPM_REGISTRY'], 'none'))
     displayName: Setup NPM Authentication
 
@@ -59,14 +60,15 @@ steps:
 
   - script: |
       set -e
+      npm i -g node-gyp@9.4.0
 
       for i in {1..5}; do # try 5 times
-        npm ci && break
-        if [ $i -eq 5 ]; then
-          echo "Npm install failed too many times" >&2
+        yarn --frozen-lockfile --check-files && break
+        if [ $i -eq 3 ]; then
+          echo "Yarn failed too many times" >&2
           exit 1
         fi
-        echo "Npm install failed $i, trying again..."
+        echo "Yarn failed $i, trying again..."
       done
     env:
       ELECTRON_SKIP_BINARY_DOWNLOAD: 1
@@ -89,11 +91,7 @@ steps:
     displayName: Create node_modules archive
 
   - ${{ if eq(parameters.VSCODE_QUALITY, 'oss') }}:
-    - script: npm run compile
-      workingDirectory: build
-      displayName: Compile /build/ folder
-
-    - script: .github/workflows/check-clean-git-state.sh
+    - script: yarn --cwd build compile && ./.github/workflows/check-clean-git-state.sh
       displayName: Check /build/ folder
 
   - ${{ if ne(parameters.VSCODE_QUALITY, 'oss') }}:
@@ -103,29 +101,24 @@ steps:
   - template: common/install-builtin-extensions.yml@self
 
   - ${{ if eq(parameters.VSCODE_QUALITY, 'oss') }}:
-    - script: npm exec -- npm-run-all -lp core-ci-pr extensions-ci-pr hygiene eslint valid-layers-check vscode-dts-compile-check tsec-compile-check
+    - script: yarn npm-run-all -lp core-ci-pr extensions-ci-pr hygiene eslint valid-layers-check vscode-dts-compile-check tsec-compile-check
       env:
         GITHUB_TOKEN: "$(github-distro-mixin-password)"
+        DISABLE_V8_COMPILE_CACHE: 1 # Disable v8 cache used by yarn v1.x, refs https://github.com/nodejs/node/issues/51555
       displayName: Compile & Hygiene (OSS)
   - ${{ else }}:
-    - script: npm exec -- npm-run-all -lp core-ci extensions-ci hygiene eslint valid-layers-check vscode-dts-compile-check tsec-compile-check
+    - script: yarn npm-run-all -lp core-ci extensions-ci hygiene eslint valid-layers-check vscode-dts-compile-check tsec-compile-check
       env:
         GITHUB_TOKEN: "$(github-distro-mixin-password)"
+        DISABLE_V8_COMPILE_CACHE: 1 # Disable v8 cache used by yarn v1.x, refs https://github.com/nodejs/node/issues/51555
       displayName: Compile & Hygiene (non-OSS)
 
   - ${{ if ne(parameters.VSCODE_QUALITY, 'oss') }}:
     - script: |
         set -e
-        npm run compile
-      displayName: Compile smoke test suites (non-OSS)
-      workingDirectory: test/smoke
-      condition: and(succeeded(), eq(variables['VSCODE_STEP_ON_IT'], 'false'))
-
-    - script: |
-        set -e
-        npm run compile
-      displayName: Compile integration test suites (non-OSS)
-      workingDirectory: test/integration/browser
+        yarn --cwd test/smoke compile
+        yarn --cwd test/integration/browser compile
+      displayName: Compile test suites (non-OSS)
       condition: and(succeeded(), eq(variables['VSCODE_STEP_ON_IT'], 'false'))
 
     - task: AzureCLI@2
@@ -171,7 +164,7 @@ steps:
         sbomEnabled: false
       displayName: Publish compilation artifact
 
-    - script: npm run download-builtin-extensions-cg
+    - script: yarn download-builtin-extensions-cg
       env:
         GITHUB_TOKEN: "$(github-distro-mixin-password)"
       displayName: Download component details of built-in extensions
